#!/bin/bash

# exit in the event that any command errors (completes with non-zero exit status)
set -e

(($#==2)) || {
    echo "Usage: $0 <input> <output>"
    exit 1
}

in=$1
out=$2

[[ -f $in ]] || {
    echo "No such file: $in"
    exit 1
}

sambamba flagstat $in > $out
echo " " >> $out
echo "READS WITH mapping_quality >= 30" >> $out
sambamba view -c -F "mapping_quality >= 30" $in >> $out
echo " " >> $out
echo "Insert sizes" >> $out
